Repository kubecost/docs, pull requests merged in 2022-05, with the labels that each got.

#201 1-click request sizing ("apply") feature guide and API reference
  api-request-recommendation-apply.md
  api-request-right-sizing.md
  controller.md
  guide-one-click-request-sizing.md
  images/one-click-request-sizing/configured-with-button.png
  images/one-click-request-sizing/confirm-dialog.png
Labels: v1.93, next release

#231 remove reference to eks:cluster-name
  aws-out-of-cluster.md
  cloud-integration.md
Labels: v1.93

#237 Windows support documentation
  windows.md
Labels: v1.94

#239 update description of Exclude Provider ID
  cloud-integration.md
Labels: v1.94

#243 Update azure-config.md
  azure-config.md
Labels: v1.94

#245 Add note about using detailed billing report
  cloud-integration.md
  gcp-out-of-cluster.md
Labels: v1.94
