Repository kubecost/docs, pull requests merged in 2022-09, with the labels that each got.

#340 Update support-channels.md
  support-channels.md
Labels: docs update

#339 Update bug-report.md
  bug-report.md
Labels: docs update

#338 Update diagnostics.md
  diagnostics.md
Labels: docs update

#341 Update troubleshoot-install.md
  troubleshoot-install.md
Labels: docs update

#335 Update custom-grafana.md
  custom-grafana.md
Labels: docs update

#371 Add quantile parameters to request sizing API v2
  api-request-right-sizing-v2.md
Labels: v1.98

#374 Link Test
  contactus.md
Labels: do-not-merge
