Repository kubecost/docs, pull requests merged in 2022-12, with the labels that each got.

#471 Move auto (1-click and continuous) request sizing setup to dedicated doc
  SUMMARY.md
  auto-request-sizing.md
  continuous-request-sizing.md
  controller.md
  guide-one-click-request-sizing.md
Labels: v1.99

#454 Remove Business and Enterprise Feature docs
  business.md
  enterprise.md
Labels: not release related

#469 Create csv-pricing.md
  csv-pricing.md
Labels: do-not-merge, v1.99

#440 PDF Allocation docs
  allocation.md
Labels: next release, v1.99
