Repository kubecost/docs, pull requests merged in 2022-11, with the labels that each got.

#430 Update req sizing v2 API doc for pipeline disable
  api-request-right-sizing-v2.md
Labels: v1.98

#434 Create federated-etl.md
  federated-etl.md
Labels: v1.98

#366 Setup: GCP workload identity configuration
  gcp-out-of-cluster.md
Labels: v1.98, do-not-merge, notes

#388 pv right sizing docs
  api-persistent-volume-right-sizing.md
Labels: v1.98, do-not-merge

#453 Remove legacy docs platform code
  CNAME
  _config.yml
  _includes/analytics.html
  _layouts/default.html
  _layouts/head.html
  assets/css/style.scss
Labels: do-not-merge
