Repository kubecost/docs, pull requests merged in 2022-10, with the labels that each got.

#372 Azure Cloud integration
  azure-out-of-cluster.md
Labels: question, not release related

#234 Update shared tenancy parameter documentation
  allocation.md
Labels: question, not release related

#258 Events
  events.md
Labels: question, new doc, not release related

#384 Delete partner-metrics.md
  partner-metrics.md
Labels: not release related

#385 Update user-management.md
  user-management.md
Labels: not release related
