Repository kubecost/docs, pull requests merged in 2023-03, with the labels that each got.

#574 Creates doc for Audit dashboard
  SUMMARY.md
  audits.md
  images/audit.png
Labels: new doc, do-not-merge, v1.101

#573 Docs: Cost Events Audit API
  SUMMARY.md
  cost-events-audit-api.md
Labels: do-not-merge, v1.101

#578 Set up email support in docs for Health & Diagnostic alerts
  alerts.md
Labels: docs update, v1.101

#582 Azure data auditing doc
  SUMMARY.md
  images/data-auditing/dataaudit-azure-acm.png
  images/data-auditing/dataaudit-azure-kubecost.png
  using-kubecost/kubecost-data-audit/README.md
  using-kubecost/kubecost-data-audit/aws-kubecost-data-audit.md
  using-kubecost/kubecost-data-audit/azure-kubecost-data-audit.md
Labels: new doc

#589 New image for Azure Data Auditing doc
  images/data-auditing/dataaudit-azure-acm.png
Labels: docs update

#595 Federated ETL Backups and Alerting
  SUMMARY.md
  federated-etl-backups-alerting.md
Labels: new doc
