Repository kubecost/docs, pull requests merged in 2023-11, with the labels that each got.

#795 Updates Container Request Right Sizing API with new parameter
  apis/apis-overview/api-request-right-sizing-v2.md
Labels: v1.107

#785 OIDC and Readonly helm configs
  install-and-configure/advanced-configuration/user-management-oidc/user-management-oidc.md
Labels: do-not-merge, v1.107

#752 Update docs to prepare for default disabling of KSM in v1.107
  architecture/ksm-metrics.md
  architecture/user-metrics.md
Labels: docs update, do-not-merge, v1.107

#799 Updates Allocations doc with changes to window picker and step sizes
  images/date-range.png
  using-kubecost/navigating-the-kubecost-ui/cost-allocation/README.md
Labels: v1.107

#783 Updates Budget API doc
  SUMMARY.md
  apis/apis-overview/budget-api.md
  apis/deprecated-apis/budgets-api-retired.md
Labels: do-not-merge, v1.107

#804 Thena / Slack ticket creation
  SUMMARY.md
  install-and-configure/install/provider-installations/install-on-plural.md
  troubleshooting/creating-a-support-ticket.md
Labels: new doc

#809 Creates new OIDC doc for Microsoft Entra ID
  .lycheeignore
  SUMMARY.md
  install-and-configure/advanced-configuration/user-management-oidc/microsoft-entra-id-oidc-integration-for-kubecost.md
  install-and-configure/advanced-configuration/user-management-oidc/user-management-oidc.md
  install-and-configure/advanced-configuration/user-management/README.md
  install-and-configure/advanced-configuration/user-management/microsoft-entra-id-saml-integration-for-kubecost.md
Labels: new doc

#812 Creates SAML Okta configuration guide
  README.md
  SUMMARY.md
  images/okta-saml-1.png
  images/okta-saml-2.png
  install-and-configure/advanced-configuration/user-management-saml/README.md
  install-and-configure/advanced-configuration/user-management-saml/microsoft-entra-id-saml-integration-for-kubecost.md
  install-and-configure/advanced-configuration/user-management-saml/okta-saml-integration.md
  install-and-configure/install/getting-started.md
Labels: new doc
