Repository kubecost/docs, pull requests merged in 2023-10, with the labels that each got.

#740 add information on new oidc helm value
  user-management-oidc.md
Labels: v1.106

#743 Creates Local Disks page
  images/localdisks.png
  local-disks.md
  savings.md
Labels: new doc

#738 Adds KC Cloud Licensing Guide with GCP Marketplace
  SUMMARY.md
  images/kc-cloud-gcp.png
  images/order-summary.png
  images/pricing-calculator.png
  kubecost-cloud-gcp-marketplace-license.md
Labels: new doc, kubecost-cloud

#745 Updates Install Troubleshooting guide with additional example
  troubleshoot-install.md
Labels: docs update, Support

#747 Creates Persistent Volume Right-Sizing Recommendation doc
  SUMMARY.md
  images/rightsizingpv.png
  savings.md
  using-kubecost/navigating-the-kubecost-ui/savings/pv-right-sizing-rec.md
Labels: new doc

#751 Fixes an error in Summary.Md that caused Spot Commander article not to display properly
  SUMMARY.md
Labels: bug

#748 Updates KC Cloud support doc
  kubecost-cloud/receiving-kubecost-cloud-support.md
Labels: kubecost-cloud

#759 Creates Admission Controller documentation
  SUMMARY.md
  using-kubecost/admission-controller.md
Labels: new doc

#769 Creates Accessibility doc
  SUMMARY.md
  images/color-palette.png
  images/legend.png
  using-kubecost/accessibility.md
Labels: new doc

#774 Creates Cluster Right Sizing Rec API doc
  apis/apis-overview/cluster-right-sizing-recommendation-api.md
Labels: new doc

#767 Creates document on cost-analyzer ClusterRoles
  install-and-configure/advanced-configuration/user-management/kubecost-cluster-roles.md
Labels: new doc

#787 Fixes anchor links in alerts.md
  install-and-configure/install/etl-backup/query-service-replicas.md
  using-kubecost/navigating-the-kubecost-ui/alerts.md
Labels: bug

#798 Adding GKE Autopilot doc
  SUMMARY.md
  install-and-configure/install/provider-installations/gke-autopilot-install.md
Labels: new doc
