Repository kubecost/docs, pull requests merged in 2023-12, with the labels that each got.

#843 Creates Kubecost Aggregator doc
  SUMMARY.md
  install-and-configure/install/multi-cluster/federated-etl/aggregator.md
Labels: new doc, 1.108

#836 Account mapping in Kubecost UI
  images/cloudcostsbreakdown.png
  install-and-configure/install/cloud-integration/README.md
Labels: 1.108

#822 Update spec-cost-prediction-api.md
  apis/apis-overview/spec-cost-prediction-api.md
Labels: 1.108

#835 Creates Cloud Cost Trends API doc, updates Allocation Trends content
  SUMMARY.md
  apis/apis-overview/allocation-trends-api.md
  apis/apis-overview/cloud-cost-api/cloud-cost-trends-api.md
  apis/apis-overview/filters-api.md
Labels: new doc, 1.108

#842 Updates Budgets doc to include labels
  using-kubecost/navigating-the-kubecost-ui/budgets.md
Labels: 1.108

#818 multi-cluster updates
  SUMMARY.md
  images/daigrams/Agent-Diagnostics-Architecture.png
  install-and-configure/install/multi-cluster/multi-cluster-diagnostics.md
  install-and-configure/install/multi-cluster/multi-cluster.md
Labels: 1.108

#837 Updates to OpenShift content
  .gitbook.yaml
  SUMMARY.md
  images/ocp-operator-installation-step-2.png
  images/ocp-operator-installation-step-3.png
  install-and-configure/install/provider-installations/openshift-kubecost-install.md
  install-and-configure/install/provider-installations/openshift-operatorhub-kubecost-install.md
  using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer.md
Labels: 1.108

#838 Renames image files to be more descriptive
  .gitbook/assets/allocations.png
  .gitbook/assets/cloud-cost-explorer.png
  .gitbook/assets/cloud-overview.png
  .gitbook/assets/cluster-details.png
  .gitbook/assets/clusters.png
  .gitbook/assets/datadog-dash.png
  .gitbook/assets/fed-etl-overview.png
  .gitbook/assets/from-web.png
  .gitbook/assets/image (2) (1).png
  .gitbook/assets/image (2) (2) (1) (1) (2) (2).png
  .gitbook/assets/new-budget.png
  .gitbook/assets/okta-saml-1.png
  .gitbook/assets/okta-saml-2.png
  .gitbook/assets/overview.png
  .gitbook/assets/qsr-arch.png
  .gitbook/assets/total-cost.png
  apis/apis-overview/allocation-trends-api.md
  images/allocations-dash-overview (2).png
  images/allocations-dash-overview (3).png
  images/rightsizing.png
  images/rightsizingcustomize (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).png
  images/rightsizingcustomize (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).png
  images/rightsizingcustomize (1).png
  images/rightsizingcustomize.png
  install-and-configure/advanced-configuration/user-management-saml/microsoft-entra-id-saml-integration-for-kubecost.md
  install-and-configure/install/etl-backup/query-service-replicas.md
  integrations/import-kubecost-data-into-microsoft-power-bi.md
  integrations/integrating-kubecost-with-datadog.md
  kubecost-cloud/using-the-kubecost-cloud-ui/README.md
  using-kubecost/navigating-the-kubecost-ui/README.md
  using-kubecost/navigating-the-kubecost-ui/budgets.md
  using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer.md
  using-kubecost/navigating-the-kubecost-ui/clusters-dashboard.md
  using-kubecost/navigating-the-kubecost-ui/cost-allocation/README.md
Labels: infrastructure
