Repository kubecost/docs, pull requests merged in 2024-02, with the labels that each got.

#890 Removes version mentions from 2.0 docs
  apis/apis-overview/api-request-recommendation-apply.md
  apis/deprecated-apis/budgets-api-retired.md
  install-and-configure/advanced-configuration/controller/turndown-schedule-migration-guide.md
  install-and-configure/advanced-configuration/network-costs-configuration.md
  install-and-configure/install/provider-installations/istio-rancher.md
  troubleshooting/diagnostics.md
  troubleshooting/etl-repair.md
  troubleshooting/http-profiling.md
  using-kubecost/navigating-the-kubecost-ui/assets.md
Labels: enhancement

#900 Adds section to Savings Action doc for YAML configuration
  using-kubecost/navigating-the-kubecost-ui/savings/savings-actions.md
Labels: 2.1

#888 Document Aggregator diagnostic APIs
  SUMMARY.md
  apis/apis-overview/api-aggregator-diagnostics.md
Labels: do-not-merge, 2.1

#903 Delists KC Cloud docs from Summary.md
  SUMMARY.md
Labels: versioning

#894 Makes Aggregator API endpoints only documented endpoints in 2.0 docs
  apis/apis-overview/allocation-trends-api.md
  apis/apis-overview/api-allocation.md
  apis/apis-overview/api-request-right-sizing-v2.md
  apis/apis-overview/apis-overview.md
  apis/apis-overview/assets-api.md
  apis/apis-overview/filters-api.md
Labels: versioning

#908 Creates Fed ETL Migration Guide to Aggregator
  SUMMARY.md
  images/aggregator-architecture.png
  install-and-configure/install/kubecostv2.md
  install-and-configure/install/multi-cluster/federated-etl/aggregator.md
  install-and-configure/install/multi-cluster/federated-etl/federated-etl-migration-guide.md
  install-and-configure/install/multi-cluster/federated-etl/federated-etl.md
Labels: new doc
