Repository kubecost/docs, pull requests merged in 2024-04, with the labels that each got.

#959 Creates External Costs page
  SUMMARY.md
  images/externalcosts.png
  using-kubecost/navigating-the-kubecost-ui/external-costs.md
Labels: 2.2

#937 Creates Carbon Costs doc
  SUMMARY.md
  images/carboncosts.png
  using-kubecost/carbon-costs.md
Labels: 2.2

#948 Add quantile-of-aggregate request sizing to doc
  apis/savings-apis/api-request-right-sizing-v2.md
Labels: 2.2

#958 Misc. docs fixes for V2.2
  apis/savings-apis/api-request-right-sizing-v2.md
  architecture/containerstats-pipeline.md
  install-and-configure/advanced-configuration/custom-prom/aws-amp-integration.md
  install-and-configure/advanced-configuration/custom-prom/custom-prom.md
  install-and-configure/advanced-configuration/custom-prom/gcp-gmp-integration.md
  install-and-configure/advanced-configuration/custom-prom/grafana-cloud-integration.md
  install-and-configure/advanced-configuration/custom-prom/grafana-mimir-integration.md
  install-and-configure/install/kubecostv2.md
  troubleshooting/diagnostics.md
  using-kubecost/navigating-the-kubecost-ui/collections.md
Labels: 2.2

#981 Creates External Costs API doc
  SUMMARY.md
  apis/apis-overview.md
  apis/filters-api.md
  apis/monitoring-apis/external-costs-api.md
  using-kubecost/navigating-the-kubecost-ui/external-costs.md
Labels: new doc, 2.2

#1003 Gcp data audit
  SUMMARY.md
  images/data-auditing/dataaudit-gcp-bigquery-output.png
  images/data-auditing/dataaudit-gcp-console.png
  images/data-auditing/gcp-kubecost-gke-asset.png
  images/data-auditing/kubecost-gcp-services.png
  using-kubecost/kubecost-data-audit/gcp-kubecost-data-audit.md
Labels: new doc

#944 Creates High Availability doc
  SUMMARY.md
  architecture/high-availability.md
  images/high-availability-enabled.png
  install-and-configure/install/ingress-examples.md
Labels: new doc, 2.2
